#!/bin/bash
set -e -o pipefail

SERVICE=${PWD##*/}
IMAGE=$SERVICE

VOLUME_DIR=${PWD/$(go env GOPATH)//go}
docker run -i -t --rm \
	-v /var/run/docker.sock:/var/run/docker.sock \
	-v $PWD:$VOLUME_DIR \
	-e VOLUME_DIR=$VOLUME_DIR \
	-e NARADA4D_DIR=$VOLUME_DIR/var \
	-e NARADA4D_SCHEMA=$VOLUME_DIR/schema \
	-e NARADA4D_BACKUP=/tmp/backup \
	--workdir=$VOLUME_DIR \
	cpdpro/baseimage:build-golang \
	bash -c "./install && ./test && docker build -t $IMAGE ."

export IMAGE=$(docker image inspect --format='{{.ID}}' $IMAGE)
gotmpl <docker-compose.yml.tmpl >docker-compose.yml
docker stack deploy -c docker-compose.yml $SERVICE
