FROM cpdpro/baseimage:build-golang

ENV VOLUME_DIR=/go/src/github.com/powerman/go-service-narada4d-example
ENV NARADA4D_DIR=$VOLUME_DIR/var \
    NARADA4D_SCHEMA=$VOLUME_DIR/schema \
    NARADA4D_BACKUP=/tmp/backup \
    HOME=/home/app
WORKDIR $VOLUME_DIR

CMD ["bash", "-c", "./install && ./test"]
