#!/bin/sh
usage() { echo "usage: $0 [<version>]" >&2; exit 1; }
last_ver() { sed -n "s/ *$//;s/^VERSION *//p" "$NARADA4D_SCHEMA/migrate" | tail -n 1; }

test $# -le 1                   || usage
test $# -eq 0                   && set -- $(last_ver)

test -L "$NARADA4D_DIR/.version"|| narada4d-init
test -L "$NARADA4D_DIR/.version"&& narada4d-migrate "$1"
