#!/bin/bash
export PATH=$PWD/bin:$PATH
set -x -e -o pipefail

narada4d-try-migrate
go get -v -t ./...
go test -v -race ./...
gometalinter \
	--exclude 'error return value not checked \(log\w*\.Err\(' \
	--exclude 'error return value not checked \(defer ' \
	--deadline 1m -t ./...
pkgs=$(go list ./... | grep -v /cmd/)
gotestcover -coverprofile cover.out -coverpkg $(echo $pkgs | sed 's/ /,/g') ./...
go tool cover -func cover.out
