#!/bin/bash
export PATH=$PWD/bin:$PATH
set -x -e -o pipefail

narada4d-try-migrate
go get -v -t ./...

go test -v -race ./...

gometalinter \
	--exclude 'error return value not checked \(log\w*\.Err\(' \
	--exclude 'error return value not checked \(defer ' \
	--exclude 'Errors unhandled.,LOW,HIGH' \
	--exclude 'declaration of "log" shadows' \
	--exclude 'declaration of "err" shadows' \
	--deadline 1m -t ./...

libpkgs=$(go list -f '{{if ne .Name "main"}}{{.ImportPath}}{{end}}' ./...)
gotestcover -coverprofile cover.out -coverpkg "$(echo $libpkgs | sed 's/ /,/g')" ./...
go tool cover -func cover.out
